### PR TITLE
Venteliste debugging

### PR DESCRIPTION
**Pull request by olejodd10**
Har gjort mye av koden som har med ventelisten og arrangementspåmelding ryddigere. Kan gå gjennom sammen en gang.

### CODE REVIEW

**Review by Loddfaavne — APPROVED** [review]
Looks nice, and definitely works. The code is more readable and more robust. Sverre would be proud.

**Comment by Loddfaavne** [comment]
I tested it locally and it worked splendidly, but as I merged and tested it on the server it did not. As soon as I made a test event with only one place, all other 428 participants got on the wait list. Quite unfortunate. We will figure it out soon, but it has probably something to do with the database on the server.

**Comment by Loddfaavne** [comment]
Screenshot from 2022-01-30 13-23-56

**Comment by Loddfaavne** [comment]
It was not possible however to delete the event. I got a 500 internal server error.
It was possible though to edit the event strangely enough.

**Comment by olejodd10** [comment]
The 500 internal server error happens when we previously just got "Error in sendEmail", and happens when the server can't send an email. When I tested stuff locally I actually got some email sending fails this time, which might mean that we have just been lucky so far when testing locally (?). I think we will just have to live with some email fails, but the question is how to handle them nicely. 

I made some changes to how the amount of participants is registered, that we can talk about in person. The error with 428 participants on waiting list should be easy to fix.

English is fun <3

**Comment by Loddfaavne** [comment]
Yeah, we will figure it out more in detail when we meet again. We can do this ;)

English is fun indeed <3

**Pull request merged**
